Revert "Fix export of inherited inline functions"
This reverts commit d999e903c0ffbfe650bc0179f266563a4a71a301.

Otherwise we had linking errors as the class wasn't exported at all:
ksirk/CMakeFiles/ksirk.dir/GameLogic/KsirkChatItem.cpp.o:(.data.rel.ro+0x40): undefined reference to `typeinfo for KChatBaseMessage'
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)

CCMAIL: vonreth@kde.org